
jobs:
  build:
    runs-on: Default
    steps:
      - type: script           # install + build in one step
        script-content: |
          yarn install --frozen-lockfile
          yarn build
          echo "Hello world"
        docker-image: node:18
    artifacts:
      paths:
        - dist/** => dist.zip

  bom-sca-scan:
    runs-on: Default
    
    steps:
      - type: script
        name: Simple SCA Scan
        script-content: |
          echo "🔍 Starting simplified Scantist SCA scan..."
          
          # Create directories
          mkdir -p .scantist
          mkdir -p devsecops_report
          
          # Check for parameters
          if [ -z "%SCA_BOM_DETECT_DOWNLOAD_URL%" ]; then
            echo "⚠️ Warning: SCA_BOM_DETECT_DOWNLOAD_URL not set"
            echo "Scan skipped. Please configure required parameters in TeamCity."
            exit 0
          fi
          
          # Download scanner - no Docker needed
          echo "Downloading SCA detector..."
          curl -L -o ".scantist/sca-bom-detect.jar" "%SCA_BOM_DETECT_DOWNLOAD_URL%" || echo "Download failed"
          
          # Simple check if Java is available
          if command -v java >/dev/null 2>&1; then
            echo "Running scan with available Java..."
            java -jar ".scantist/sca-bom-detect.jar" -f "%teamcity.build.checkoutDir%" -report json || echo "Scan failed"
          else
            echo "⚠️ Java not found. Scan skipped."
            echo "Make sure Java is available on the build agent."
          fi
          
          echo "✅ SCA step completed"
    
    artifacts:
      paths:
        - "devsecops_report/**" => sca-reports.zip