
jobs:
  build:
    runs-on: Ubuntu-24.04-Small
    steps:
      - type: script           # install + build in one step
        script-content: |
          yarn install --frozen-lockfile
          yarn build
          
          # SCA scan
          echo "ðŸ” Starting Scantist SCA scan..."
          
          # Set up environment variables
          SCA_PLUGIN_DIR=".scantist"
          SCA_REPORT_DIR="devsecops_report"
          SCA_JAR_NAME="sca-bom-detect.jar"
          
          # Download SCA detector if not exists
          if [[ ! -f "${SCA_PLUGIN_DIR}/${SCA_JAR_NAME}" ]]; then
            echo "[SCA] Downloading SCA detector..."
            mkdir -p "${SCA_PLUGIN_DIR}"
            curl -L "https://download.scantist.io/sca-bom-detect.jar" -o "${SCA_PLUGIN_DIR}/${SCA_JAR_NAME}"
            echo "[SCA] Download completed"
          fi
          
          # Create report directory
          mkdir -p "${SCA_REPORT_DIR}"
          
          # Run SCA scan with DevSecOps integration
          echo "[SCA] Starting scan on: %teamcity.build.checkoutDir%"
          echo "[SCA] DevSecOps integration enabled"
          
          # Environment variables are already set at the job level
          java -jar "${SCA_PLUGIN_DIR}/${SCA_JAR_NAME}" -f "%teamcity.build.checkoutDir%" --debug -report json
          
          echo "[SCA] Scan completed. Reports in: ${SCA_REPORT_DIR}"
        docker-image: wynventory/maven-node-yarn
    artifacts:
      paths:
        - dist/** => dist.zip
        - devsecops_report/** => devsecops_report.zip

  # The bom-sca-scan job has been merged into the build job for simplicity