
jobs:
  build:
    runs-on: Ubuntu-24.04-Small
    steps:
      - type: script           # install + build in one step
        script-content: |
          yarn install --frozen-lockfile
          yarn build
          echo "Hello world"
        docker-image: node:18
    artifacts:
      paths:
        - dist/** => dist.zip

  bom-sca-scan:
    runs-on: Ubuntu-24.04-Small
    dependencies:
      - build
    use-artifacts:
      - job: build
        source-paths:
          - dist/**
    
    steps:
      - type: script
        name: SCA Scan with Maven
        script-content: |
          echo "This is a minimal test script with Maven Docker image"
          echo "Running on agent: Ubuntu-24.04-Small"
          echo "Current directory: $(pwd)"
          echo "Success!"
        docker-image: maven:3.8-openjdk-11