version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      
      - run:
          name: Build
          command: yarn build
      
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
