version: 2.1

# Global environment variables
parameters:
  sca_bom_detect_download_url:
    type: string
    default: "https://download.scantist.io/sca-bom-detect.jar"

orbs:
  sca: scan/sca@0.0.11

# Define jobs
jobs:
  build:
    docker:
      - image: cimg/node:18.0
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      
      - run:
          name: Build
          command: yarn build
      
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build-test-workflow:
    jobs:
      - build
      - sca/sca-scan:
          requires:
            - build
          context: scantist-security
          environment:
            SCA_BOM_DETECT_DOWNLOAD_URL: << pipeline.parameters.sca_bom_detect_download_url >>
            DEVSECOPS_TOKEN: ${DEVSECOPS_TOKEN}
            DEVSECOPS_IMPORT_URL: ${DEVSECOPS_IMPORT_URL}